import streamlit as st

from .common.utils import parse_response
from .common.datasets import add_records


st.set_page_config(layout="wide")

st.title("🎈 Rapid Prompts Parser")
st.subheader(
    "Parses the prompt-response pairs generated by LLMs and uploads into argilla dataset"
)


def main():
    response_from_state = (
        st.session_state["generated_response"]
        if "generated_response" in st.session_state
        else ""
    )
    pairs = []

    with st.form("parse_response_form"):
        response = st.text_area(
            "Response",
            value=response_from_state,
            placeholder="Paste the response generate by an LLM",
        )
        pairs = parse_response(response)
        is_submitted = st.form_submit_button("Parse")
        if is_submitted:
            st.markdown(response)

    with st.form("upload_form"):
        pairs = st.data_editor(pairs)
        is_submitted = st.form_submit_button("Upload")
        if is_submitted:
            add_records(pairs)


main()
